insert into member(lastname, firstname,phone, active)
values ('Gajecki', 'Marek', '48656575122', 1)

insert into adult(memberID, street, homeNo, city, state, zip, expirationDate)
values(1, 'Mickiewicza', '30', 'Krakow', 'Malopolska', '30500', GETDATE()+(60*60))

insert into member(lastname, firstname, phone, active)
values ('Gajecki', 'Michal', '11223344556', 1)
insert into member(lastname, firstname, phone, active)
values ('Gajecki', 'MAciek', '11223344556', 1)
insert into member(lastname, firstname, phone, active)
values ('Gajecki', 'adam', '11223344556', 1)

insert into juvenile(memberID, birthDate, adult_memberID)
values(2,GETDATE()-(60*60),1)
insert into juvenile(memberID, birthDate, adult_memberID)
values(3,GETDATE()-(60*60),1)
insert into juvenile(memberID, birthDate, adult_memberID)
values(4,GETDATE()-(60*60),1)

INSERT INTO film (title, director, description) VALUES ('Skazani na Shawshank', 'Frank Darabont', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.')
INSERT INTO film (title, director, description) VALUES ('Ojciec chrzestny', 'Francis Ford Coppola', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.')
INSERT INTO film (title, director, description) VALUES ('Ojciec chrzestny II', 'Francis Ford Coppola', 'The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.')
INSERT INTO film (title, director, description) VALUES ('Dobry, zly i brzydki', 'Sergio Leone', 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.')
INSERT INTO film (title, director, description) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'The lives of two mob hit men, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.')
INSERT INTO film (title, director, description) VALUES ('Lista Schindlera', 'Steven Spielberg', 'In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.')
INSERT INTO film (title, director, description) VALUES ('Incepcja', 'Christopher Nolan', 'In a world where technology exists to enter the human mind through dream invasion, a highly skilled thief is given a final chance at redemption which involves executing his toughest job to date: Inception.')
INSERT INTO film (title, director, description) VALUES ('Dwunastu gniewnych ludzi', 'Sidney Lumet', 'A dissenting juror in a murder trial slowly manages to convince the others that the case is not as obviously clear as it seemed in court.')
INSERT INTO film (title, director, description) VALUES ('Lot nad kukulczym gniazdem', 'Milos Forman', 'Upon arrival at a mental institution, a brash rebel rallies the patients together to take on the oppressive Nurse Ratched, a woman more a dictator than a nurse.')
INSERT INTO film (title, director, description) VALUES ('Mroczny rycerz', 'Christopher Nolan', 'Batman, Gordon and Harvey Dent are forced to deal with the chaos unleashed by an anarchist mastermind known only as the Joker, as it drives each of them to their limits.')
INSERT INTO film (title, director, description) VALUES ('Gwiezdne wojny, czesc V: Imperium kontratakuje', 'Irvin Kershner', 'While Luke takes advanced Jedi training from Yoda, his friends are relentlessly pursued by Darth Vader as part of his plan to capture Luke.')
INSERT INTO film (title, director, description) VALUES ('Wladca pierscieni: Powrót króla', 'Peter Jackson', 'The former Fellowship of the Ring prepare for the final battle for Middle Earth, while Frodo & Sam approach Mount Doom to destroy the One Ring.')
INSERT INTO film (title, director, description) VALUES ('Siedmiu samurajów', 'Akira Kurosawa', 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.')
INSERT INTO film (title, director, description) VALUES ('Podziemny krag', 'David Fincher', 'An office employee and a soap salesman build a global organization to help vent male aggression.')
INSERT INTO film (title, director, description) VALUES ('Gwiezdne wojny', 'George Lucas', 'Luke Skywalker leaves his home planet, teams up with other rebels, and tries to save Princess Leia from the evil clutches of Darth Vader.')
INSERT INTO film (title, director, description) VALUES ('Chlopcy z ferajny', 'Martin Scorsese', 'Henry Hill and his friends work their way up through the mob hierarchy.')
INSERT INTO film (title, director, description) VALUES ('Casablanca', 'Michael Curtiz', 'Set in unoccupied Africa during the early days of World War II: An American expatriate meets a former lover, with unforeseen complications.')
INSERT INTO film (title, director, description) VALUES ('Miasto Boga', 'Fernando Meirelles', 'Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.')
INSERT INTO film (title, director, description) VALUES ('Wladca pierscieni: Druzyna pierscienia', 'Peter Jackson', 'In a small village in the Shire a young Hobbit named Frodo has been entrusted with an ancient Ring. Now he must embark on an Epic quest to the Cracks of Doom in order to destroy it.')
INSERT INTO film (title, director, description) VALUES ('Pewnego razu na Dzikim Zachodzie', 'Sergio Leone', 'Epic story of a mysterious stranger with a harmonica who joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.')
INSERT INTO film (title, director, description) VALUES ('Okno na podwórze', 'Alfred Hitchcock', 'A wheelchair bound photographer spies on his neighbours from his apartment window and becomes convinced one of them has committed murder.')
INSERT INTO film (title, director, description) VALUES ('Poszukiwacze zaginionej arki', 'Steven Spielberg', 'Archeologist and adventurer Indiana Jones is hired by the US government to find the Ark of the Covenant before the Nazis.')
INSERT INTO film (title, director, description) VALUES ('Matrix', 'Andy Wachowski', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.')
INSERT INTO film (title, director, description) VALUES ('Psychoza', 'Alfred Hitchcock', 'A young woman steals $40,000 from her employer''s client, and subsequently encounters a young motel proprietor too long under the domination of his mother.')
INSERT INTO film (title, director, description) VALUES ('Podejrzani', 'Bryan Singer', 'A boat has been destroyed, criminals are dead, and the key to this mystery lies with the only survivor and his twisted, convoluted story beginning with five career crooks in a seemingly random police lineup.')
INSERT INTO film (title, director, description) VALUES ('Milczenie owiec', 'Jonathan Demme', 'A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.')
INSERT INTO film (title, director, description) VALUES ('Toy Story 3', 'Lee Unkrich', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it''s up to Woody to convince the other toys that they weren''t abandoned and to return home.')
INSERT INTO film (title, director, description) VALUES ('Siedem', 'David Fincher', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his modus operandi.')
INSERT INTO film (title, director, description) VALUES ('To wspaniale zycie', 'Frank Capra', 'An angel helps a compassionate but despairingly frustrated businessman by showing what life would have been like if he never existed.')
INSERT INTO film (title, director, description) VALUES ('Memento', 'Christopher Nolan', 'A man, suffering from short-term memory loss, uses notes and tattoos to hunt for the man he thinks killed his wife.')
INSERT INTO film (title, director, description) VALUES ('Wladca pierscieni: Dwie wieze', 'Peter Jackson', 'Frodo and Sam continue on to Mordor in their mission to destroy the One Ring. Whilst their former companions make new allies and launch an assault on Isengard.')
INSERT INTO film (title, director, description) VALUES ('Bulwar Zachodzacego Slonca', 'Billy Wilder', 'A hack screenwriter writes a screenplay for a former silent-film star who has faded into Hollywood obscurity.')
INSERT INTO film (title, director, description) VALUES ('Forrest Gump', 'Robert Zemeckis', 'Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny, eludes him.')
INSERT INTO film (title, director, description) VALUES ('Leon zawodowiec', 'Luc Besson', 'Professional assassin Leon reluctantly takes care of 12-year-old Mathilda, a neighbor whose parents are killed, and teaches her his trade.')
INSERT INTO film (title, director, description) VALUES ('Dr Strangelove, czyli jak przestalem sie martwic i pokochalem bombe', 'Stanley Kubrick', 'An insane general starts a process to nuclear holocaust that a war room of politicians and generals frantically try to stop.')
INSERT INTO film (title, director, description) VALUES ('Czas Apokalipsy', 'Francis Ford Coppola', 'During the on-going Vietnam War, Captain Willard is sent on a dangerous mission into Cambodia to assassinate a renegade Green Beret who has set himself up as a God among a local tribe.')
INSERT INTO film (title, director, description) VALUES ('Obywatel Kane', 'Orson Welles', 'Following the death of a publishing tycoon, news reporters scramble to discover the meaning of his final utterance.')
INSERT INTO film (title, director, description) VALUES ('Pólnoc, pólnocny zachód', 'Alfred Hitchcock', 'A hapless New York advertising executive is mistaken for a government agent by a group of foreign spies, and is pursued across the country while he looks for a way to survive.')
INSERT INTO film (title, director, description) VALUES ('American Beauty', 'Sam Mendes', 'Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation for his daughter''s attractive friend.')
INSERT INTO film (title, director, description) VALUES ('Wiezien nienawisci', 'Tony Kaye', 'A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.')
INSERT INTO film (title, director, description) VALUES ('Taksówkarz', 'Martin Scorsese', 'A mentally unstable Vietnam war veteran works as nighttime taxi driver in a city whose perceived decadence and sleaze feeds his urge to violently lash out, attempting to save a teenage prostitute in the process.')
INSERT INTO film (title, director, description) VALUES ('Terminator 2: Dzien sadu', 'James Cameron', 'The cyborg who once tried to kill Sarah Connor must now protect her teenage son, John Connor, from an even more powerful and advanced Terminator.')
INSERT INTO film (title, director, description) VALUES ('Szeregowiec Ryan', 'Steven Spielberg', 'Following the Normandy Landings, a group of US soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.')
INSERT INTO film (title, director, description) VALUES ('Zawrót glowy', 'Alfred Hitchcock', 'A San Francisco detective suffering from acrophobia investigates the strange activities of an old friend''s wife, all the while becoming dangerously obsessed with her.')
INSERT INTO film (title, director, description) VALUES ('Amelia', 'Jean-Pierre Jeunet', 'Amelie, an innocent and naive girl in Paris, with her own sense of justice, decides to help those around her and along the way, discovers love.')
INSERT INTO film (title, director, description) VALUES ('Obcy - ósmy pasazer Nostromo', 'Ridley Scott', 'A mining ship, investigating a suspected SOS, lands on a distant planet. The crew discovers some strange creatures and investigates.')
INSERT INTO film (title, director, description) VALUES ('WALL·E', 'Andrew Stanton', 'In the distant future, a small waste collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.')
INSERT INTO film (title, director, description) VALUES ('Spirited Away: W krainie bogów', 'Hayao Miyazaki', 'In the middle of her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and monsters; where humans are changed into animals; and a bathhouse for these creatures.')
INSERT INTO film (title, director, description) VALUES ('Lsnienie', 'Stanley Kubrick', 'A family heads to an isolated hotel for the winter where an evil and spiritual presence influences the father into violence, while his psychic son sees horrific forebodings from the past and of the future.')
INSERT INTO film (title, director, description) VALUES ('Sciezki chwaly', 'Stanley Kubrick', 'When soldiers in WW1 refuse to continue with an impossible attack, their superiors decide to make an example of them.')
INSERT INTO film (title, director, description) VALUES ('Lawrence z Arabii', 'David Lean', 'Epic rumination on a flamboyant and controversial British military figure and his conflicted loyalties during wartime service.')
INSERT INTO film (title, director, description) VALUES ('Czarny labedz', 'Darren Aronofsky', 'A ballet dancer wins the lead in "Swan Lake" and is perfect for the role of the delicate White Swan, but slowly loses her mind as she becomes more and more like the evil twin sister of the White Swan, the Black Swan.')
INSERT INTO film (title, director, description) VALUES ('Podwójne ubezpieczenie', 'Billy Wilder', 'An insurance rep lets himself be talked into a murder/insurance fraud scheme that arouses an insurance investigator''s suspicions.')
INSERT INTO film (title, director, description) VALUES ('Pianista', 'Roman Polanski', 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.')
INSERT INTO film (title, director, description) VALUES ('Mechaniczna pomarancza', 'Stanley Kubrick', 'In future Britain, charismatic delinquent Alex DeLarge is jailed and volunteers for an experimental aversion therapy developed by the government in an effort to solve society''s crime problem... but not all goes to plan.')
INSERT INTO film (title, director, description) VALUES ('Zabic drozda', 'Robert Mulligan', 'Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his kids against prejudice.')
INSERT INTO film (title, director, description) VALUES ('Zycie na podsluchu', 'Florian Henckel von Donnersmarck', 'In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.')
INSERT INTO film (title, director, description) VALUES ('Swiatla wielkiego miasta', 'Charles Chaplin', 'The Tramp struggles to help a blind flower girl he has fallen in love with.')
INSERT INTO film (title, director, description) VALUES ('M - morderca', 'Fritz Lang', 'When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.')
INSERT INTO film (title, director, description) VALUES ('Infiltracja', 'Martin Scorsese', 'Two men from opposite sides of the law are undercover within the Massachusetts State Police and the Irish mafia, but violence and bloodshed boil when discoveries are made, and the moles are dispatched to find out their enemy''s identities.')
INSERT INTO film (title, director, description) VALUES ('Obcy - decydujace starcie', 'James Cameron', 'The planet from Obcy - ósmy pasazer Nostromo has been colonized, but contact is lost. This time, the rescue team has impressive firepower, but will it be enough?')
INSERT INTO film (title, director, description) VALUES ('Zakochany bez pamieci', 'Michel Gondry', 'A couple undergo a procedure to erase each other from their memories when their relationship turns sour, but it is only through the process of loss that they discover what they had to begin with.')
INSERT INTO film (title, director, description) VALUES ('Requiem dla snu', 'Darren Aronofsky', 'The drug-induced utopias of four Coney Island individuals are shattered when their addictions become stronger.')
INSERT INTO film (title, director, description) VALUES ('Okret', 'Wolfgang Petersen', 'The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.')
INSERT INTO film (title, director, description) VALUES ('Trzeci czlowiek', 'Carol Reed', 'Arriving in Vienna, Holly Martins learns that his friend Harry Lime, who has invited him, recently died in a car accident.')
INSERT INTO film (title, director, description) VALUES ('Wsciekle psy', 'Quentin Tarantino', 'After a simple jewelery heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.')
INSERT INTO film (title, director, description) VALUES ('Tajemnice Los Angeles', 'Curtis Hanson', 'A shooting at an all night diner is investigated by three LA policemen in their own unique ways.')
INSERT INTO film (title, director, description) VALUES ('Chinatown', 'Roman Polanski', 'A private detective investigating an adultery case stumbles on to a scheme of murder that has something to do with water.')
INSERT INTO film (title, director, description) VALUES ('Dzisiejsze czasy', 'Charles Chaplin', 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.')
INSERT INTO film (title, director, description) VALUES ('Skarb Sierra Madre', 'John Huston', 'Fred C. Dobbs and Bob Curtin, both down on their luck in Tampico, Mexico in 1925, meet up with a grizzled... See full summary »')
INSERT INTO film (title, director, description) VALUES ('Zycie jest piekne', 'Roberto Benigni', 'A Jewish man has a wonderful romance with the help of his humour, but must use that same quality to protect his son in a Nazi death camp.')
INSERT INTO film (title, director, description) VALUES ('Powrót do przyszlosci', 'Robert Zemeckis', 'In 1985, Doc Brown invents time travel; in 1955, Marty McFly accidentally prevents his parents from meeting, putting his own existence at stake.')
INSERT INTO film (title, director, description) VALUES ('Monty Python i swiety Graal', 'Terry Gilliam', 'King Arthur and his knights embark on a low-budget search for the Grail, encountering many very silly obstacles.')
INSERT INTO film (title, director, description) VALUES ('Prestiz', 'Christopher Nolan', 'The rivalry between two magicians is exacerbated when one of them performs the ultimate illusion.')
INSERT INTO film (title, director, description) VALUES ('Labirynt Fauna', 'Guillermo del Toro', 'In the fascist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.')
INSERT INTO film (title, director, description) VALUES ('Wsciekly byk', 'Martin Scorsese', 'An emotionally self-destructive boxer''s journey through life, as the violence and temper that leads him to the top in the ring, destroys his life outside it.')
INSERT INTO film (title, director, description) VALUES ('Cinema Paradiso', 'Giuseppe Tornatore', 'A filmmaker recalls his childhood, when he fell in love with the movies at his village''s theater and formed a deep friendship with the theater''s projectionist.')
INSERT INTO film (title, director, description) VALUES ('Deszczowa piosenka', 'Stanley Donen', 'A silent film production company and cast make a difficult transition to sound.')
INSERT INTO film (title, director, description) VALUES ('Pól zartem, pól serio', 'Billy Wilder', 'When two musicians witness a mob hit, they flee the state in an all female band disguised as women, but further complications set in.')
INSERT INTO film (title, director, description) VALUES ('Most na rzece Kwai', 'David Lean', 'After settling his differences with a Japanese PoW camp commander, a British colonel co-operates to oversee his men''s construction of a railway bridge for their captors - while oblivious to a plan by the Allies to destroy it.')
INSERT INTO film (title, director, description) VALUES ('Rashomon', 'Akira Kurosawa', 'A heinous crime and its aftermath are recalled from differing points of view.')
INSERT INTO film (title, director, description) VALUES ('Wszystko o Ewie', 'Joseph L. Mankiewicz', 'An ingenue insinuates herself in to the company of an established but aging stage actress and her circle of theater friends.')
INSERT INTO film (title, director, description) VALUES ('Amadeusz', 'Milos Forman', 'The incredible story of Wolfgang Amadeus Mozart, told in flashback mode by Antonio Salieri - now confined to an insane asylum.')
INSERT INTO film (title, director, description) VALUES ('Dawno temu w Ameryce', 'Sergio Leone', 'A former Prohibition-era Jewish gangster returns to Brooklyn over 30 years later, where he once again must confront the ghosts and regrets of his old life.')
INSERT INTO film (title, director, description) VALUES ('Zielona mila', 'Frank Darabont', 'The story about the lives of guards on death row leading up to the execution of black man accused of child murder & rape, who has the power of faith healing.')
INSERT INTO film (title, director, description) VALUES ('Full Metal Jacket', 'Stanley Kubrick', 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow Marine recruits from their brutal basic training to the bloody street fighting set in 1968 Hue, Vietnam.')
INSERT INTO film (title, director, description) VALUES ('Zlodzieje rowerów', 'Vittorio De Sica', 'A man and his son search for a stolen bicycle vital for his job.')
INSERT INTO film (title, director, description) VALUES ('2001: Odyseja kosmiczna', 'Stanley Kubrick', 'Mankind finds a mysterious, obviously artificial, artifact buried on the moon and, with the intelligent computer HAL, sets off on a quest.')
INSERT INTO film (title, director, description) VALUES ('Dyktator', 'Charles Chaplin', 'In Chaplin''s satire on Nazi Germany, dictator Adenoid Hynkel has a double... a poor Jewish barber... who one day is mistaken for Hynkel.')
INSERT INTO film (title, director, description) VALUES ('Braveheart - Waleczne serce', 'Mel Gibson', 'William Wallace, a commoner, unites the 13th Century Scots in their battle to overthrow English rule.')
INSERT INTO film (title, director, description) VALUES ('Bekarty wojny', 'Quentin Tarantino', 'In Nazi-occupied France during World War II, a group of Jewish-American soldiers known as "The Basterds" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis.')
INSERT INTO film (title, director, description) VALUES ('Garsoniera', 'Billy Wilder', 'A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.')
INSERT INTO film (title, director, description) VALUES ('Upadek', 'Oliver Hirschbiegel', 'Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator''s final days in his Berlin bunker at the end of WWII.')
INSERT INTO film (title, director, description) VALUES ('Odlot', 'Pete Docter', 'By tying thousands of balloon to his home, 78-year-old Carl Fredricksen sets out to fulfill his lifelong dream to see the wilds of South America. Right after lifting off, however, he learns he isn''t alone on his journey, since Russell, a wilderness explorer 70 years his junior, has inadvertently become a stowaway on the trip.')
INSERT INTO film (title, director, description) VALUES ('Gran Torino', 'Clint Eastwood', 'Disgruntled Korean War vet Walt Kowalski sets out to reform his neighbor, a young Hmong teenager, who tried to steal Kowalski''s prized possession: his 1972 Gran Torino.')
INSERT INTO film (title, director, description) VALUES ('Metropolis', 'Fritz Lang', 'In a futuristic city sharply divided between the working class and the city planners, the son of the city''s mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.')
INSERT INTO film (title, director, description) VALUES ('Gladiator', 'Ridley Scott', 'When a Roman general is betrayed and his family murdered by a corrupt prince, he comes to Rome as a gladiator to seek revenge.')
INSERT INTO film (title, director, description) VALUES ('Zadlo', 'George Roy Hill', 'In 1930s Chicago, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker.')
INSERT INTO film (title, director, description) VALUES ('Bez przebaczenia', 'Clint Eastwood', 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.')
INSERT INTO film (title, director, description) VALUES ('Sokól maltanski', 'John Huston', 'A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.')
INSERT INTO film (title, director, description) VALUES ('Czlowiek slon', 'David Lynch', 'A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak. Behind his monstrous facade, there is revealed a person of intelligence and sensitivity.')
INSERT INTO film (title, director, description) VALUES ('Oldboy', 'Chan-wook Park', 'After being kidnapped and imprisoned for 15 years, Oh Dae-Su is released, only to find that he must find his captor in 5 days.')
INSERT INTO film (title, director, description) VALUES ('Mr. Smith jedzie do Waszyngtonu', 'Frank Capra', 'A naive man is appointed to fill a vacancy in the US Senate. His plans promptly collide with political corruption, but he doesn''t back down.')
INSERT INTO film (title, director, description) VALUES ('Sin City - miasto grzechu', 'Frank Miller', 'A film that explores the dark and miserable town, Basin City, and tells the story of three different people, all caught up in violent corruption.')
INSERT INTO film (title, director, description) VALUES ('Na nabrzezach', 'Elia Kazan', 'An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.')
INSERT INTO film (title, director, description) VALUES ('Rebeka', 'Alfred Hitchcock', 'When a naive young woman marries a rich widower and settles in his gigantic mansion, she finds the memory of the first wife maintaining a grip on her husband and the servants.')
INSERT INTO film (title, director, description) VALUES ('Indiana Jones i ostatnia krucjata', 'Steven Spielberg', 'When Dr. Henry Jones Sr. suddenly goes missing while pursuing the Holy Grail, eminent archaeologist Indiana Jones must follow in his father''s footsteps and stop the Nazis.')
INSERT INTO film (title, director, description) VALUES ('Gwiezdne wojny, czesc VI: Powrót Jedi', 'Richard Marquand', 'After rescuing Han Solo from the palace of Jabba the Hutt, the Rebels attempt to destroy the Second Death Star, while Luke Skywalker tries to bring his father back to the Light Side of the Force.')
INSERT INTO film (title, director, description) VALUES ('Szklana pulapka', 'John McTiernan', 'New York cop John McClane gives terrorists a dose of their own medicine as they hold hostages in an LA office building.')
INSERT INTO film (title, director, description) VALUES ('Wielka ucieczka', 'John Sturges', 'Allied POWs plan for several hundred of their number to escape from a German camp during World War II.')
INSERT INTO film (title, director, description) VALUES ('Ksiezniczka Mononoke', 'Hayao Miyazaki', 'On a journey to find the cure for a Tatarigami''s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.')
INSERT INTO film (title, director, description) VALUES ('Batman - Poczatek', 'Christopher Nolan', 'The story of how Bruce Wayne became what he was destined to be: Batman.')
INSERT INTO film (title, director, description) VALUES ('Siódma pieczec', 'Ingmar Bergman', 'A man seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.')
INSERT INTO film (title, director, description) VALUES ('Szczeki', 'Steven Spielberg', 'When a gigantic great white shark begins to menace the small island community of Amity, a police chief, a marine scientist and grizzled fisherman set out to stop it.')
INSERT INTO film (title, director, description) VALUES ('Hotel Ruanda', 'Terry George', 'The true-life story of Paul Rusesabagina, a hotel manager who housed over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda.')
INSERT INTO film (title, director, description) VALUES ('Lowca androidów', 'Ridley Scott', 'Deckard, a blade runner, has to track down and terminate 4 replicants who hijacked a ship in space and have returned to earth seeking their maker.')
INSERT INTO film (title, director, description) VALUES ('Slumdog, milioner z ulicy', 'Danny Boyle', 'A Mumbai teen who grew up in the slums, becomes a contestant on the Indian version of "Who Wants To Be A Millionaire?" He is arrested under suspicion of cheating, and while being interrogated, events from his life history are shown which explain why he knows the answers.')
INSERT INTO film (title, director, description) VALUES ('Fargo', 'Joel Coen', 'Jerry Lundegaard''s inept crime falls apart due to his and his henchmen''s bungling and the persistent police work of pregnant Marge Gunderson.')
INSERT INTO film (title, director, description) VALUES ('General', 'Clyde Bruckman', 'When Union spies steal an engineer''s beloved locomotive, he pursues it single handedly and straight through enemy lines.')
INSERT INTO film (title, director, description) VALUES ('To nie jest kraj dla starych ludzi', 'Ethan Coen', 'Violence and mayhem ensue after a hunter stumbles upon some dead bodies, a stash of heroin and more than $2 million in cash near the Rio Grande.')
INSERT INTO film (title, director, description) VALUES ('Goraczka', 'Michael Mann', 'A Los Angeles crime saga, "Heat" focuses on the lives of two men on opposite sides of the law - one a detective; the other a thief.')
INSERT INTO film (title, director, description) VALUES ('Czarnoksieznik z krainy Oz', 'Victor Fleming', 'Dorothy Gale is swept away to a magical land in a tornado and embarks on a quest to see the Wizard who can help her return home.')
INSERT INTO film (title, director, description) VALUES ('Za kilka dolarów wiecej', 'Sergio Leone', 'Two bounty hunters with completely different intentions team up to track down a Western outlaw.')
INSERT INTO film (title, director, description) VALUES ('Dotyk zla', 'Orson Welles', 'Stark, perverse story of murder, kidnapping, and police corruption in Mexican border town.')
INSERT INTO film (title, director, description) VALUES ('Straz przyboczna', 'Akira Kurosawa', 'A crafty ronin comes to a town divided by two criminal gangs and decides to play them against each other to free the town.')
INSERT INTO film (title, director, description) VALUES ('Ran', 'Akira Kurosawa', 'An elderly lord abdicates to his three sons, and the two corrupt ones turn against him.')
INSERT INTO film (title, director, description) VALUES ('Swiadek oskarzenia', 'Billy Wilder', 'Agatha Christie tale of a man on trial for murder: a trial featuring surprise after surprise.')
INSERT INTO film (title, director, description) VALUES ('Tam, gdzie rosna poziomki', 'Ingmar Bergman', 'After living a life marked by coldness, an aging professor is forced to confront the emptiness of his existence.')
INSERT INTO film (title, director, description) VALUES ('Grobowiec swietlików', 'Isao Takahata', 'A tragic film covering a young boy and his little sister''s struggle to survive in Japan during World War II.')
INSERT INTO film (title, director, description) VALUES ('Przekret', 'Guy Ritchie', 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers, and supposedly Jewish jewelers fight to track down a priceless stolen diamond.')
INSERT INTO film (title, director, description) VALUES ('Szósty zmysl', 'M. Night Shyamalan', 'A boy who communicates with spirits that don''t know they''re dead seeks the help of a disheartened child psychologist.')
INSERT INTO film (title, director, description) VALUES ('Annie Hall', 'Woody Allen', 'Neurotic New York comedian Alvy Singer falls in love with the ditsy Annie Hall.')
INSERT INTO film (title, director, description) VALUES ('Lowca jeleni', 'Michael Cimino', 'An in-depth examination of the way that the Vietnam war affects the lives of people in a small industrial town in the USA.')
INSERT INTO film (title, director, description) VALUES ('Donnie Darko', 'Richard Kelly', 'A troubled teenager is plagued by visions of a large bunny rabbit that manipulates him to commit a series of crimes, after narrowly escaping a bizarre accident.')
INSERT INTO film (title, director, description) VALUES ('Dystrykt 9', 'Neill Blomkamp', 'An extraterrestrial race forced to live in slum-like conditions on Earth suddenly finds a kindred spirit in a government agent who is exposed to their biotechnology.')
INSERT INTO film (title, director, description) VALUES ('Nieugiety Luke', 'Stuart Rosenberg', 'A man refuses to conform to life in a rural prison.')
INSERT INTO film (title, director, description) VALUES ('Big Lebowski', 'Joel Coen', '"Dude" Lebowski, mistaken for a millionaire Lebowski, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.')
INSERT INTO film (title, director, description) VALUES ('Nieznajomi z pociagu', 'Alfred Hitchcock', 'A psychotic socialite confronts a pro tennis star with a theory on how two complete strangers can get away with murder...a theory that he plans to implement.')
INSERT INTO film (title, director, description) VALUES ('W samo poludnie', 'Fred Zinnemann', 'A marshall, personally compelled to face a returning deadly enemy, finds that his own town refuses to help him.')
INSERT INTO film (title, director, description) VALUES ('Ich noce', 'Frank Capra', 'A spoiled heiress, running away from her family, is helped by a man who''s actually a reporter looking for a story. But then he falls for her...')
INSERT INTO film (title, director, description) VALUES ('Kill Bill', 'Quentin Tarantino', 'The Bride wakes up after a long coma. The baby that she carried before entering the coma is gone. The only thing on her mind is to have revenge on the assassination team that betrayed her - a team she was once part of.')
INSERT INTO film (title, director, description) VALUES ('Król lew', 'Roger Allers', 'Tricked into thinking he killed his father, a guilt ridden lion cub flees into exile and abandons his identity as the future King.')
INSERT INTO film (title, director, description) VALUES ('Pluton', 'Oliver Stone', 'A young recruit in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.')
INSERT INTO film (title, director, description) VALUES ('Avatar', 'James Cameron', 'A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.')
INSERT INTO film (title, director, description) VALUES ('Wszystko za zycie', 'Sean Penn', 'After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.')
INSERT INTO film (title, director, description) VALUES ('Az poleje sie krew', 'Paul Thomas Anderson', 'A story about family, greed, religion, and oil, centered around a turn-of-the-century prospector in the early days of the business.')
INSERT INTO film (title, director, description) VALUES ('Toy Story', 'John Lasseter', 'A cowboy toy is profoundly threatened and jealous when a fancy spaceman toy supplants him as top toy in a boy''s room.')
INSERT INTO film (title, director, description) VALUES ('Oslawiona', 'Alfred Hitchcock', 'A woman is asked to spy on a group of Nazi friends in South America. How far will she have to go to ingratiate herself with them?')
INSERT INTO film (title, director, description) VALUES ('Za wszelka cene', 'Clint Eastwood', 'A hardened trainer/manager works with a determined woman in her attempt to establish herself as a boxer.')
INSERT INTO film (title, director, description) VALUES ('Butch Cassidy i Sundance Kid', 'George Roy Hill', 'Two Western bank/train robbers flee to Bolivia when the law gets too close.')
INSERT INTO film (title, director, description) VALUES ('Wschód slonca', 'F.W. Murnau', 'A married farmer falls under the spell of a slatternly woman from the city, who tries to convince him to drown his wife.')
INSERT INTO film (title, director, description) VALUES ('Przeminelo z wiatrem', 'Victor Fleming', 'American classic in which a manipulative woman and a roguish man carry on a turbulent love affair in the American south during the Civil War and Reconstruction.')
INSERT INTO film (title, director, description) VALUES ('Trainspotting', 'Danny Boyle', 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.')
INSERT INTO film (title, director, description) VALUES ('Goraczka zlota', 'Charles Chaplin', 'The Tramp goes the Klondike in search of gold and finds it and more.')
INSERT INTO film (title, director, description) VALUES ('Czlowiek z blizna', 'Brian De Palma', 'In 1980 Miami, a determined Cuban immigrant takes over a drug empire while succumbing to greed. (Cartel not Mafia)')
INSERT INTO film (title, director, description) VALUES ('Przezylismy wojne', 'John Frankenheimer', 'A former Korean War POW is brainwashed by Communists into becoming a political assassin. But another former prisoner may know how to save him.')
INSERT INTO film (title, director, description) VALUES ('Zapasnik', 'Darren Aronofsky', 'A faded professional wrestler must retire, but finds his quest for a new life outside the ring a dispiriting struggle.')
INSERT INTO film (title, director, description) VALUES ('Grona gniewu', 'John Ford', 'A poor Midwest family is forced off of their land. They travel to California, suffering the misfortunes of the homeless in the Great Depression.')
INSERT INTO film (title, director, description) VALUES ('Ben Hur', 'William Wyler', 'When a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge.')
INSERT INTO film (title, director, description) VALUES ('The Social Network', 'David Fincher', 'A chronicle of the founding of Facebook, the social-networking Web site.')
INSERT INTO film (title, director, description) VALUES ('Wielki sen', 'Howard Hawks', 'Private detective Philip Marlowe is hired by a rich family. Before the complex case is over, he''s seen murder, blackmail, and what might be love.')
INSERT INTO film (title, director, description) VALUES ('Dzien swistaka', 'Harold Ramis', 'A weatherman finds himself living the same day over and over again.')
INSERT INTO film (title, director, description) VALUES ('Absolwent', 'Mike Nichols', 'Recent college graduate Benjamin Braddock is trapped into an affair with Mrs. Robinson, who happens to be the wife of his father''s business partner and then finds himself falling in love with her teenage daughter, Elaine.')
INSERT INTO film (title, director, description) VALUES ('Zywot Briana', 'Terry Jones', 'Brian is born on the original Christmas, in the stable next door. He spends his life being mistaken for a messiah.')
INSERT INTO film (title, director, description) VALUES ('Amores perros', 'Alejandro González Ińárritu', 'A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life''s harsh realities, all in the name of love.')
INSERT INTO film (title, director, description) VALUES ('Gdzie jest Nemo?', 'Andrew Stanton', 'A father-son underwater adventure featuring Nemo, a boy clownfish, stolen from his coral reef home. His timid father must then travel to Sydney and search Sydney Harbour to find Nemo.')
INSERT INTO film (title, director, description) VALUES ('Ultimatum Bourne''a', 'Paul Greengrass', 'Jason Bourne dodges a ruthless CIA official and his agents from a new assassination program while searching for the origins of his life as a trained killer.')
INSERT INTO film (title, director, description) VALUES ('The King''s Speech', 'Tom Hooper', 'The story of King George VI of Britain, his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it.')
INSERT INTO film (title, director, description) VALUES ('Terminator', 'James Cameron', 'A human-looking, apparently unstoppable cyborg is sent from the future to kill Sarah Connor; Kyle Reese is sent to stop it.')
INSERT INTO film (title, director, description) VALUES ('Najlepsze lata naszego zycia', 'William Wyler', 'Three WWII veterans return home to small-town America to discover that they and their families have been irreparably changed.')
INSERT INTO film (title, director, description) VALUES ('Brzdac', 'Charles Chaplin', 'The Tramp cares for an abandoned child, but events put that relationship in jeopardy.')
INSERT INTO film (title, director, description) VALUES ('Pietno smierci', 'Akira Kurosawa', 'Kanji Watanabe is a longtime bureaucrat in a city office who, along with the rest of the office, spends his entire working life doing nothing... See full summary »')
INSERT INTO film (title, director, description) VALUES ('Porachunki', 'Guy Ritchie', 'Four London working class stiffs pool their money to put one in a high stakes card game, but things go wrong and they end up owing half a million pounds and having one week to come up with the cash.')
INSERT INTO film (title, director, description) VALUES ('Stan przy mnie', 'Rob Reiner', 'After the death of a friend, a writer recounts a boyhood journey to find a body of a missing boy')
INSERT INTO film (title, director, description) VALUES ('Cos', 'John Carpenter', 'Scientists in the Antarctic are confronted by a shape-shifting alien that assumes the appearance of the people that it kills.')
INSERT INTO film (title, director, description) VALUES ('Jak wytresowac smoka', 'Dean DeBlois', 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.')
INSERT INTO film (title, director, description) VALUES ('Cena strachu', 'Henri-Georges Clouzot', 'In a decrepit South American village, men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe.')
INSERT INTO film (title, director, description) VALUES ('Sekret jej oczu', 'Juan José Campanella', 'A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior - both of which still haunt him decades later.')
INSERT INTO film (title, director, description) VALUES ('Kasyno', 'Martin Scorsese', 'Greed, deception, money, power, and murder occur between two mobster best friends and a trophy wife over a gambling empire.')
INSERT INTO film (title, director, description) VALUES ('Dwanascie malp', 'Terry Gilliam', 'In a future world devastated by disease, a convict is sent back in time to gather information about the man-made virus that wiped out most of the human population on the planet.')
INSERT INTO film (title, director, description) VALUES ('V jak vendetta', 'James McTeigue', 'A shadowy freedom fighter known only as "V" uses terrorist tactics to fight against his totalitarian society. Upon rescuing a girl from the secret police, he also finds his best chance at having an ally.')
INSERT INTO film (title, director, description) VALUES ('Pieskie popoludnie', 'Sidney Lumet', 'A man robs a bank to pay for his lover''s operation; it turns into a hostage situation and a media circus.')
INSERT INTO film (title, director, description) VALUES ('Ratatuj', 'Brad Bird', 'Remy is a young rat in the French countryside who arrives in Paris, only to find out that his cooking idol is dead. When he makes an unusual alliance with a restaurant''s new garbage boy, the culinary and personal adventures begin despite Remy''s family''s skepticism and the rat-hating world of humans.')
INSERT INTO film (title, director, description) VALUES ('Widmo', 'Henri-Georges Clouzot', 'The wife of a cruel headmaster and his mistress conspire to kill him, but after the murder is committed, his body disappears, and strange events begin to plague the two women.')
INSERT INTO film (title, director, description) VALUES ('Gandhi', 'Richard Attenborough', 'Biography of Mahatma Gandhi , the lawyer who became the famed leader of the Indian revolts against the British through his philosophy of non-violent protest.')
INSERT INTO film (title, director, description) VALUES ('Star Trek', 'J.J. Abrams', 'A chronicle of the early days of James T. Kirk and his fellow USS Enterprise crew members.')
INSERT INTO film (title, director, description) VALUES ('Osiem i pól', 'Federico Fellini', 'A harried movie director retreats into his memories and fantasies.')
INSERT INTO film (title, director, description) VALUES ('Mój sasiad Totoro', 'Hayao Miyazaki', 'When two girls move to the country to be near their ailing mother, they have adventures with the wonderous forest spirits who live nearby.')
INSERT INTO film (title, director, description) VALUES ('Narzeczona ksiecia', 'Rob Reiner', 'A classic fairy tale, with swordplay, giants, an evil prince, a beautiful princess, and yes, some kissing (as read by a kindly grandfather).')
INSERT INTO film (title, director, description) VALUES ('Noc mysliwego', 'Charles Laughton', 'A religious fanatic marries a gullible widow whose young children are reluctant to tell him where their real daddy hid $10,000 he''d stolen in a robbery.')
INSERT INTO film (title, director, description) VALUES ('Wyrok w Norymberdze', 'Stanley Kramer', 'In 1948, an American court in occupied Germany tries four Nazi judges for war crimes.')
INSERT INTO film (title, director, description) VALUES ('Prawdziwe mestwo', 'Ethan Coen', 'A tough U.S. Marshal helps a stubborn young woman track down her father''s murderer.')
INSERT INTO film (title, director, description) VALUES ('Bilardzista', 'Robert Rossen', 'An up-and-coming pool player plays a long-time champion in a single high-stakes match.')
INSERT INTO film (title, director, description) VALUES ('Iniemamocni', 'Brad Bird', 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.')
INSERT INTO film (title, director, description) VALUES ('Zabójstwo', 'Stanley Kubrick', 'Crooks plan and execute a daring racetrack robbery.')
INSERT INTO film (title, director, description) VALUES ('La strada', 'Federico Fellini', 'A carefree girl is sold to a traveling entertainer, consequently enduring physical and emotional pain along the way.')
INSERT INTO film (title, director, description) VALUES ('Buntownik z wyboru', 'Gus Van Sant', 'Will Hunting, a janitor at MIT, has a gift for mathematics but needs help from a psychologist to find direction in his life.')
INSERT INTO film (title, director, description) VALUES ('Czterysta batów', 'François Truffaut', 'Intensely touching story of a misunderstood young adolescent who left without attention, delves into a life of petty crime.')
INSERT INTO film (title, director, description) VALUES ('Siec', 'Sidney Lumet', 'A TV network cynically exploits a deranged ex-TV anchor''s ravings and revelations about the media for their own profit.')
INSERT INTO film (title, director, description) VALUES ('Bitwa o Algier', 'Gillo Pontecorvo', 'An account of the bloodiest revolution in modern history.')
INSERT INTO film (title, director, description) VALUES ('Najpierw strzelaj, potem zwiedzaj', 'Martin McDonagh', 'Holed up in Bruges, Belgium after a difficult job, two hit men begin to differ on their views of life and death as they become used to local customs.')
INSERT INTO film (title, director, description) VALUES ('Dzika banda', 'Sam Peckinpah', 'An aging group of outlaws look for one last big score as the "traditional" American West is disappearing around them.')
INSERT INTO film (title, director, description) VALUES ('Motyl i skafander', 'Julian Schnabel', 'The true story of Elle editor Jean-Dominique Bauby who suffers a stroke and has to live with an almost totally paralyzed body; only his left eye isn''t paralyzed.')
INSERT INTO film (title, director, description) VALUES ('Tramwaj zwany pozadaniem', 'Elia Kazan', 'Disturbed Blanche DuBois moves in with her sister in New Orleans and is tormented by her brutish brother-in-law while her reality crumbles around her.')
INSERT INTO film (title, director, description) VALUES ('Persona', 'Ingmar Bergman', 'A nurse is put in charge of an actress who can''t talk and finds that the actress''s persona is melding with hers.')
INSERT INTO film (title, director, description) VALUES ('Stalag 17', 'Billy Wilder', 'When two escaping American World War II prisoners are killed, the German POW camp barracks black marketeer, J.J. Sefton, is suspected of being an informer.')
INSERT INTO film (title, director, description) VALUES ('Egzorcysta', 'William Friedkin', 'When a teenager is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.')
INSERT INTO film (title, director, description) VALUES ('Kto sie boi Virginii Woolf?', 'Mike Nichols', 'A bitter aging couple with the help of alcohol, use a young couple to fuel anguish and emotional pain towards each other.')
INSERT INTO film (title, director, description) VALUES ('Meczenstwo Joanny d''Arc', 'Carl Theodor Dreyer', 'A chronicle of the trial of Jeanne d''Arc on charges of heresy, and the efforts of her ecclesiastical jurists to force Jeanne to recant her claims of holy visions.')
INSERT INTO film (title, director, description) VALUES ('Ludzkie dzieci', 'Alfonso Cuarón', 'In 2027, in a chaotic world in which humans can no longer procreate, a former activist agrees to help transport a miraculously pregnant woman to a sanctuary at sea, where her child''s birth may help scientists save the future of humankind.')
INSERT INTO film (title, director, description) VALUES ('M jak morderstwo', 'Alfred Hitchcock', 'An ex-tennis pro carries out a plot to murder his wife. When things go wrong, he improvises a brilliant plan B.')
INSERT INTO film (title, director, description) VALUES ('Szlachectwo zobowiazuje', 'Robert Hamer', 'A distant poor relative of the Duke of D''Ascoyne plots to inherit the title by murdering the eight other heirs who stand ahead of him in the line of succession.')
INSERT INTO film (title, director, description) VALUES ('Na Zachodzie bez zmian', 'Lewis Milestone', 'A young soldier faces profound disillusionment in the soul-destroying horror of World War I.')
INSERT INTO film (title, director, description) VALUES ('Ed Wood', 'Tim Burton', 'The mostly true story of the legendary director of awful movies and his strange group of friends and actors.')
INSERT INTO film (title, director, description) VALUES ('Fanny i Aleksander', 'Ingmar Bergman', 'The title characters are children in the exuberant and colorful Ekdahl household in a Swedish town early in the twentieth century... See full summary »')
INSERT INTO film (title, director, description) VALUES ('127 godzin', 'Danny Boyle', 'A mountain climber becomes trapped under a boulder while canyoneering alone near Moab, Utah and resorts to desperate measures in order to survive.')
INSERT INTO film (title, director, description) VALUES ('Pozwól mi wejsc', 'Tomas Alfredson', 'Oscar, an overlooked and bullied boy, finds love and revenge through Eli, a beautiful but peculiar girl who turns out to be a vampire.')
INSERT INTO film (title, director, description) VALUES ('Rocky', 'John G. Avildsen', 'A small time boxer gets a once in a lifetime chance to fight the heavyweight champ in a bout in which he strives to go the distance for his self-respect.')
INSERT INTO film (title, director, description) VALUES ('Mary and Max', 'Adam Elliot', 'A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.')
INSERT INTO film (title, director, description) VALUES ('Duza ryba', 'Tim Burton', 'A story about a son trying to learn more about his dying father by reliving stories and myths his father told him about himself.')
INSERT INTO film (title, director, description) VALUES ('Magnolia', 'Paul Thomas Anderson', 'An epic mosaic of several interrelated characters in search of happiness, forgiveness, and meaning in the San Fernando Valley.')
INSERT INTO film (title, director, description) VALUES ('Manhattan', 'Woody Allen', 'A divorced New Yorker currently dating a high-schooler brings himself to look for love in the mistress of his best friend instead.')
INSERT INTO film (title, director, description) VALUES ('Rzeka tajemnic', 'Clint Eastwood', 'With a childhood tragedy that overshadowed their lives, three men are reunited by circumstance when one loses a daughter.')
INSERT INTO film (title, director, description) VALUES ('Barry Lyndon', 'Stanley Kubrick', 'An Irish rogue wins the heart of a rich widow and assumes her dead husband''s position in 18th Century aristocracy.')
INSERT INTO film (title, director, description) VALUES ('Noce Cabirii', 'Federico Fellini', 'A waifish prostitute wanders the streets of Rome looking for true love but finds only heartbreak.')
INSERT INTO film (title, director, description) VALUES ('Festen', 'Thomas Vinterberg', 'At Helge''s 60th birthday party, some unpleasant family truths are revealed.')
INSERT INTO film (title, director, description) VALUES ('Patton', 'Franklin J. Schaffner', 'The World War II phase of the controversial American general''s career is depicted.')
INSERT INTO film (title, director, description) VALUES ('Kill Bill 2', 'Quentin Tarantino', 'The murderous Bride continues her vengeance quest against her ex-boss, Bill, and his two remaining associates; his younger brother Budd, and Bill''s latest flame Elle.')
INSERT INTO film (title, director, description) VALUES ('Dziecko Rosemary', 'Roman Polanski', 'A young couple move into a new apartment, only to be surrounded by peculiar neighbors and occurrences. When the wife becomes mysteriously pregnant, paranoia over the safety of her unborn child begins controlling her life.')
INSERT INTO film (title, director, description) VALUES ('Rzymskie wakacje', 'William Wyler', 'A bored and sheltered princess escapes her guardians and falls in love with an American newsman in Rome.')
INSERT INTO film (title, director, description) VALUES ('Truman Show', 'Peter Weir', 'An insurance salesman/adjuster discovers his entire life is actually a TV show.')
INSERT INTO film (title, director, description) VALUES ('Kacza zupa', 'Leo McCarey', 'Rufus T. Firefly is named president/dictator of bankrupt Freedonia and declares war on neighboring Sylvania over the love of wealthy Mrs. Teasdale.')
INSERT INTO film (title, director, description) VALUES ('Dziewczyna Pietaszek', 'Howard Hawks', 'A newspaper editor uses every trick in the book to keep his ace reporter ex-wife from remarrying.')
INSERT INTO film (title, director, description) VALUES ('Infernal affairs: Piekielna gra', 'Wai-keung Lau', 'A story between a mole in the police department and an undercover cop. Their objectives are the same: to find out who is the mole, and who is the cop.')
INSERT INTO film (title, director, description) VALUES ('Fighter', 'David O. Russell', 'A look at the early years of boxer "Irish" Micky Ward and his brother who helped train him before going pro in the mid 1980s.')
INSERT INTO film (title, director, description) VALUES ('Listy z Iwo Jimy', 'Clint Eastwood', 'The story of the battle of Iwo Jima between the United States and Imperial Japan during World War II, as told from the perspective of the Japanese who fought it.')
INSERT INTO film (title, director, description) VALUES ('Piraci z Karaibów: Klatwa Czarnej Perly', 'Gore Verbinski', 'Blacksmith Will Turner teams up with eccentric pirate "Captain" Jack Sparrow to save his love, the governor''s daughter, from Jack''s former pirate allies, who are now undead.')
INSERT INTO film (title, director, description) VALUES ('Ruchomy zamek Hauru', 'Hayao Miyazaki', 'When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking home.')
INSERT INTO film (title, director, description) VALUES ('Sherlock Jr.', 'Buster Keaton', 'A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend''s father''s pocketwatch.')
INSERT INTO film (title, director, description) VALUES ('Arszenik i stare koronki', 'Frank Capra', 'A drama critic learns on his wedding day that his beloved maiden aunts are homicidal maniacs, and that insanity runs in his family.')
INSERT INTO film (title, director, description) VALUES ('Spragnieni milosci', 'Kar Wai Wong', 'A man and a woman move in to neighboring Hong Kong apartments and form a bond when they both suspect their spouses of extra-marital activities.')
INSERT INTO film (title, director, description) VALUES ('Filadelfijska opowiesc', 'George Cukor', 'When a rich woman''s ex-husband and a tabloid-type reporter turn up just before her planned remarriage, she begins to learn the truth about herself.')
INSERT INTO film (title, director, description) VALUES ('Harvey', 'Henry Koster', 'Elwood P. Dowd is a mild-mannered, pleasant man, who just happens (he says) to have an invisible friend resembling a 6-foot rabbit.')
INSERT INTO film (title, director, description) VALUES ('Detektyw', 'Joseph L. Mankiewicz', 'A man who loves games and theater invites his wife''s lover to meet him, setting up a battle of wits with potentially deadly results.')
INSERT INTO film (title, director, description) VALUES ('A Christmas Story', 'Bob Clark', 'Ralphie has to convince his parents, teachers, and Santa that a Red Ryder BB gun really is the perfect gift for the 1940''s.')
INSERT INTO film (title, director, description) VALUES ('Miasto gniewu', 'Paul Haggis', 'Several stories interweave during two days in Los Angeles involving a collection of inter-related characters... See full summary »')
INSERT INTO film (title, director, description) VALUES ('Czlowiek, który zabil Liberty Valance''a', 'John Ford', 'A senator, who became famous for killing a notorious outlaw, returns for the funeral of an old friend and tells the truth about his deed.')
INSERT INTO film (title, director, description) VALUES ('Trzy kolory: Czerwony', 'Krzysztof Kieslowski', 'Final entry in a trilogy of films dealing with contemporary French society concerns a model who discovers her neighbour is keen on invading people''s privacy.')
INSERT INTO film (title, director, description) VALUES ('Kick-Ass', 'Matthew Vaughn', 'Dave Lizewski is an unnoticed high school student and comic book fan who one day decides to become a super-hero, even though he has no powers, training or meaningful reason to do so.')
INSERT INTO film (title, director, description) VALUES ('Sznur', 'Alfred Hitchcock', 'Two young men strangle their "inferior" classmate, hide his body in their apartment, and invite his friends and family to a dinner party as a means to challenge the "perfection" of their crime.')

insert into medium (mediumName) VALUES ('DVD')
insert into medium (mediumName) VALUES ('Blu-ray')
insert into medium (mediumName) VALUES ('VHS')

INSERT INTO item (filmID, mediumID) VALUES (1, 1)
INSERT INTO item (filmID, mediumID) VALUES (1, 2)
INSERT INTO item (filmID, mediumID) VALUES (1, 3)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (1, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (2, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)
INSERT INTO copy(mediumID, filmID, onLoan) VALUES (3, 1, 1)

-- dalsza czesc pliku to na razie jakies testy
--Mamy uzytkownikow, mamy kopie, dodajemy wypozyczenia:
declare @ds int
--exec insertLoan @copy_Id=7, @member_ID=1, @discount=@ds output
--exec insertLoan @copy_Id=8, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=9, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=10, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=11, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=12, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=13, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=14, @member_ID=1, @discount=@ds output
exec insertLoan @copy_Id=15, @member_ID=1, @discount=@ds output
select * from film
select * from loan
select * from loanhist
select * from member
delete from loan where copyID=32
delete from loan where copyID=33
declare @ds int
exec insertLoan @copy_Id=35, @member_ID=2, @discount=@ds output
select @ds

drop database OurRental

select COUNT(*) from loanhist where memberID=1